<?php

class WomenFashion extends Fashion implements Core{
    private $breadth, $length, $shoulder, $waist;

    public function setFashion($material, $color, $attire)
    {
        parent::setFashion($material, $color, $attire); // TODO: Change the autogenerated stub
    }

    public function getFashion()
    {
        return parent::getFashion(); // TODO: Change the autogenerated stub
    }

    //Interface method redeclaration
    public function setCore($breadth, $length)
    {
        $this -> breadth = $breadth;
        $this -> length = $length;
    }

    //Interface method redeclaration
    public function getCore()
    {
        return "Breadth : ".$this->breadth ."</br>Length : ".$this->length;
    }


    public function setShoulder($shoulder)
    {
        $this->shoulder = $shoulder;
    }

    /**
     * @return mixed
     */
    public function getShoulder()
    {
        return "Shoulder : ".$this->shoulder;
    }

    /**
     * @param mixed $waist
     */
    public function setWaist($waist)
    {
        $this->waist = $waist;
    }

    /**
     * @return mixed
     */
    public function getWaist()
    {
        return 'Waist : '.$this->waist;
    }

    //encapsulation - calling a method from the parent class
    public function Bye()
    {
        echo $this -> goodBye();
    }
}